insert into CentroDeCusto (Codigo,Descricao) values('1        ','ADMINISTRACAO/SOCIOS                    ')
insert into CentroDeCusto (Codigo,Descricao) values('11       ','ADMINISTRACAO/SOCIOS                    ')
insert into CentroDeCusto (Codigo,Descricao) values('1100     ','SOCIOS                                  ')
insert into CentroDeCusto (Codigo,Descricao) values('110001   ','SOCIOS                                  ')
insert into CentroDeCusto (Codigo,Descricao) values('1101     ','ADMINISTRACAO SANCHEZ                   ')
insert into CentroDeCusto (Codigo,Descricao) values('110101   ','ADMINISTRACAO SANCHEZ                   ')
insert into CentroDeCusto (Codigo,Descricao) values('1102     ','ADMINISTRACAO FINI COMERCIALIZADORA     ')
insert into CentroDeCusto (Codigo,Descricao) values('110201   ','ADMINISTRACAO FINI COMERCIALIZADORA     ')
insert into CentroDeCusto (Codigo,Descricao) values('1103     ','ADMINISTRACAO FINI FRANQUIAS            ')
insert into CentroDeCusto (Codigo,Descricao) values('110301   ','ADMINISTRACAO FINI FRANQUIAS            ')
insert into CentroDeCusto (Codigo,Descricao) values('1104     ','RECURSOS HUMANOS                        ')
insert into CentroDeCusto (Codigo,Descricao) values('110401   ','ADM RH                                  ')
insert into CentroDeCusto (Codigo,Descricao) values('110402   ','SEG. TRABALHO/SAUDE                     ')
insert into CentroDeCusto (Codigo,Descricao) values('1105     ','TECNOLOGIA DA INFORMACAO                ')
insert into CentroDeCusto (Codigo,Descricao) values('110501   ','ADM TI                                  ')
insert into CentroDeCusto (Codigo,Descricao) values('1106     ','COMPRAS                                 ')
insert into CentroDeCusto (Codigo,Descricao) values('110601   ','ADM.COMPRAS                             ')
insert into CentroDeCusto (Codigo,Descricao) values('1107     ','ADMINISTRACAO FILIAIS                   ')
insert into CentroDeCusto (Codigo,Descricao) values('110701   ','ADM. PERNAMBUCO                         ')
insert into CentroDeCusto (Codigo,Descricao) values('1199     ','ADMINISTRACAO - LOJAS                   ')
insert into CentroDeCusto (Codigo,Descricao) values('119901   ','ADM. JARDIM SUL                         ')
insert into CentroDeCusto (Codigo,Descricao) values('119902   ','ADM. ELDORADO                           ')
insert into CentroDeCusto (Codigo,Descricao) values('119903   ','ADM. SHOP. JUNDIAI - LOJA               ')
insert into CentroDeCusto (Codigo,Descricao) values('119904   ','ADM. MOOCA PLAZA                        ')
insert into CentroDeCusto (Codigo,Descricao) values('119905   ','ADM. PATIO LIMEIRA                      ')
insert into CentroDeCusto (Codigo,Descricao) values('119906   ','ADM. CAMPINAS SHOP.                     ')
insert into CentroDeCusto (Codigo,Descricao) values('119907   ','ADM. PQ. DOM PEDRO                      ')
insert into CentroDeCusto (Codigo,Descricao) values('119908   ','ADM. PLAZA SUL                          ')
insert into CentroDeCusto (Codigo,Descricao) values('119909   ','ADM. GRANJA VIANA                       ')
insert into CentroDeCusto (Codigo,Descricao) values('119910   ','ADM. SHOP. TAMBORE                      ')
insert into CentroDeCusto (Codigo,Descricao) values('119911   ','ADM. VALE SUL                           ')
insert into CentroDeCusto (Codigo,Descricao) values('119912   ','ADM. SANTANA PARQUE SHOPPING            ')
insert into CentroDeCusto (Codigo,Descricao) values('119913   ','ADM. SHOP. PQ DAS BANDEIRAS             ')
insert into CentroDeCusto (Codigo,Descricao) values('119914   ','ADM. TIJUCA SHOPPING - RJ               ')
insert into CentroDeCusto (Codigo,Descricao) values('119915   ','ADM. SAO BERNARDO PLAZA                 ')
insert into CentroDeCusto (Codigo,Descricao) values('119916   ','ADM. SHOP. CENTER NORTE                 ')
insert into CentroDeCusto (Codigo,Descricao) values('119917   ','ADM. POLO SHOP. INDAIATUBA              ')
insert into CentroDeCusto (Codigo,Descricao) values('119918   ','ADM. SHOP. LITORAL PLAZA                ')
insert into CentroDeCusto (Codigo,Descricao) values('119919   ','ADM. IGUATEMI RIB.PRETO                 ')
insert into CentroDeCusto (Codigo,Descricao) values('119920   ','ADM. SHOP. IGUATEMI ESPLANADA           ')
insert into CentroDeCusto (Codigo,Descricao) values('119921   ','ADM. FINI STORE                         ')
insert into CentroDeCusto (Codigo,Descricao) values('119922   ','ADM. SHOP. TABOAO                       ')
insert into CentroDeCusto (Codigo,Descricao) values('119923   ','ADM. SHOP. NACOES BAURU                 ')
insert into CentroDeCusto (Codigo,Descricao) values('119924   ','ADM. SHOP. CENTER VALE                  ')
insert into CentroDeCusto (Codigo,Descricao) values('119925   ','ADM. SHOP. IGUATEMI RIO PRETO           ')
insert into CentroDeCusto (Codigo,Descricao) values('119926   ','ADM. LOJA RODOVIARIA DE CAMPINAS        ')
insert into CentroDeCusto (Codigo,Descricao) values('119927   ','ADM. IGUATEMI ALPHAVILLE                ')
insert into CentroDeCusto (Codigo,Descricao) values('119928   ','ADM. PARKSHOPPING CAMPO GRANDE          ')
insert into CentroDeCusto (Codigo,Descricao) values('119929   ','ADM. SHOP. NACOES LIMEIRA               ')
insert into CentroDeCusto (Codigo,Descricao) values('119930   ','ADM. MARKET PLAZA - CAMPOS DO JORDAO    ')
insert into CentroDeCusto (Codigo,Descricao) values('119931   ','ADM. SHOP. IGUATEMI SAO CARLOS          ')
insert into CentroDeCusto (Codigo,Descricao) values('119932   ','ADM. VIA CAMPOS - CAMPOS DO JORDAO      ')
insert into CentroDeCusto (Codigo,Descricao) values('119933   ','ADM. SHOP. METRO ITAQUERA               ')
insert into CentroDeCusto (Codigo,Descricao) values('119934   ','ADM. UNIMART CAMPINAS                   ')
insert into CentroDeCusto (Codigo,Descricao) values('119935   ','ADM. CAXIAS SHOPPING                    ')
insert into CentroDeCusto (Codigo,Descricao) values('119936   ','ADM. SHOP. RAPOSO                       ')
insert into CentroDeCusto (Codigo,Descricao) values('119937   ','ADM. SHOP. BOTAFOGO PRAIA               ')
insert into CentroDeCusto (Codigo,Descricao) values('119938   ','ADM. SHOP. SAO GONCALO                  ')
insert into CentroDeCusto (Codigo,Descricao) values('119939   ','ADM. SHOP. CARIOCA SHOPPING             ')
insert into CentroDeCusto (Codigo,Descricao) values('119940   ','ADM. SHOP. GRANDE RIO                   ')
insert into CentroDeCusto (Codigo,Descricao) values('119941   ','ADM. VIA PARQUE - SHOP. ANALIA FRANCO   ')
insert into CentroDeCusto (Codigo,Descricao) values('119942   ','ADM. SHOP. ABC                          ')
insert into CentroDeCusto (Codigo,Descricao) values('119943   ','ADM. SHOP. JUNDIAI - QUIOSQUE           ')
insert into CentroDeCusto (Codigo,Descricao) values('119944   ','ADM. RIBEIRAO SHOP.                     ')
insert into CentroDeCusto (Codigo,Descricao) values('119945   ','ADM. SHOP. SANTA URSULA                 ')
insert into CentroDeCusto (Codigo,Descricao) values('119946   ','ADM. SHOP. METROPOLITANO                ')
insert into CentroDeCusto (Codigo,Descricao) values('119947   ','ADM. SHOP. FASHION MALL                 ')
insert into CentroDeCusto (Codigo,Descricao) values('119948   ','ADM. SHOP. GUADALUPE                    ')
insert into CentroDeCusto (Codigo,Descricao) values('119949   ','ADM. SHOP. RIO DESIGN SHOP.             ')
insert into CentroDeCusto (Codigo,Descricao) values('119950   ','ADM. BOULEVARD SAO GONCALO              ')
insert into CentroDeCusto (Codigo,Descricao) values('119951   ','ADM. SHOP. PIRACICABA                   ')
insert into CentroDeCusto (Codigo,Descricao) values('119952   ','ADM. SHOP. LIGHT                        ')
insert into CentroDeCusto (Codigo,Descricao) values('119953   ','ADM. SHOP. BOTUCATU                     ')
insert into CentroDeCusto (Codigo,Descricao) values('119954   ','ADM. SHOP. TIETE PLAZA                  ')
insert into CentroDeCusto (Codigo,Descricao) values('119955   ','ADM. SHOP. ATIBAIA                      ')
insert into CentroDeCusto (Codigo,Descricao) values('119956   ','ADM. GRAND PLAZA SHOPPING               ')
insert into CentroDeCusto (Codigo,Descricao) values('119957   ','ADM. SHOP. GOLDEN SQUARE                ')
insert into CentroDeCusto (Codigo,Descricao) values('119958   ','ADM. SHOP. BARRA                        ')
insert into CentroDeCusto (Codigo,Descricao) values('119959   ','ADM. SHOP. IGUATEMI SOROCABA            ')
insert into CentroDeCusto (Codigo,Descricao) values('119960   ','ADM. SHOP. MORUMBI                      ')
insert into CentroDeCusto (Codigo,Descricao) values('119961   ','ADM. SHOP.INTERNACIONAL GUARULHOS       ')
insert into CentroDeCusto (Codigo,Descricao) values('119962   ','ADM. PARQUE SHOP. MAIA                  ')
insert into CentroDeCusto (Codigo,Descricao) values('119963   ','ADM. OFFICE SHOPPING OSASCO             ')
insert into CentroDeCusto (Codigo,Descricao) values('119964   ','ADM. SHOP. SAO CAETANO                  ')
insert into CentroDeCusto (Codigo,Descricao) values('119965   ','ADM. IGUATEMI CAMPINAS                  ')
insert into CentroDeCusto (Codigo,Descricao) values('2        ','VENDAS                                  ')
insert into CentroDeCusto (Codigo,Descricao) values('21       ','VENDAS MERCADO INTERNO                  ')
insert into CentroDeCusto (Codigo,Descricao) values('2100     ','ADMINISTRACAO VENDAS                    ')
insert into CentroDeCusto (Codigo,Descricao) values('210001   ','ADM. VENDAS                             ')
insert into CentroDeCusto (Codigo,Descricao) values('2101     ','VENDAS MERCADO INTERNO                  ')
insert into CentroDeCusto (Codigo,Descricao) values('210101   ','VENDAS REGIONAL SP - DISTRIBUICAO       ')
insert into CentroDeCusto (Codigo,Descricao) values('210102   ','VENDAS REGIONAL SP - ATACADO            ')
insert into CentroDeCusto (Codigo,Descricao) values('210103   ','VENDAS REGIONAL RJ/ES/MG                ')
insert into CentroDeCusto (Codigo,Descricao) values('210104   ','VENDAS REGIONAL CO/TO                   ')
insert into CentroDeCusto (Codigo,Descricao) values('210105   ','VENDAS REGIONAL RJ/ES - DISTRIBUICAO    ')
insert into CentroDeCusto (Codigo,Descricao) values('210106   ','VENDAS REGIONAL NE                      ')
insert into CentroDeCusto (Codigo,Descricao) values('210107   ','VENDAS REGIONAL MG                      ')
insert into CentroDeCusto (Codigo,Descricao) values('210108   ','VENDAS REGIONAL NO                      ')
insert into CentroDeCusto (Codigo,Descricao) values('210109   ','VENDAS REGIONAL PR                      ')
insert into CentroDeCusto (Codigo,Descricao) values('210110   ','VENDAS REGIONAL RS                      ')
insert into CentroDeCusto (Codigo,Descricao) values('210111   ','VENDAS REGIONAL SC                      ')
insert into CentroDeCusto (Codigo,Descricao) values('210112   ','VENDAS REGIONAL SPI / MG                ')
insert into CentroDeCusto (Codigo,Descricao) values('210113   ','VENDAS - KEY ACCOUNT                    ')
insert into CentroDeCusto (Codigo,Descricao) values('2102     ','OUTROS VENDAS                           ')
insert into CentroDeCusto (Codigo,Descricao) values('210201   ','TREINAMENTOS                            ')
insert into CentroDeCusto (Codigo,Descricao) values('3        ','MARKETING                               ')
insert into CentroDeCusto (Codigo,Descricao) values('31       ','MARKETING                               ')
insert into CentroDeCusto (Codigo,Descricao) values('3100     ','MARKETING                               ')
insert into CentroDeCusto (Codigo,Descricao) values('310001   ','ADM. MARKETING                          ')
insert into CentroDeCusto (Codigo,Descricao) values('310002   ','CONFEITARIA                             ')
insert into CentroDeCusto (Codigo,Descricao) values('3101     ','MARKETING - OUTROS SERVICOS             ')
insert into CentroDeCusto (Codigo,Descricao) values('310101   ','MATERIAL PROMOC. MARKETING              ')
insert into CentroDeCusto (Codigo,Descricao) values('310102   ','ROYALTIES                               ')
insert into CentroDeCusto (Codigo,Descricao) values('310103   ','FRANQUIA                                ')
insert into CentroDeCusto (Codigo,Descricao) values('310104   ','ECOMMERCE                               ')
insert into CentroDeCusto (Codigo,Descricao) values('310105   ','PESQUISA MERCADO MKT                    ')
insert into CentroDeCusto (Codigo,Descricao) values('3102     ','FEIRAS / EXPOSICOES                     ')
insert into CentroDeCusto (Codigo,Descricao) values('310201   ','FEIRA ABAD                              ')
insert into CentroDeCusto (Codigo,Descricao) values('310202   ','FEIRA APAS                              ')
insert into CentroDeCusto (Codigo,Descricao) values('310203   ','FEIRA DISNEY                            ')
insert into CentroDeCusto (Codigo,Descricao) values('310204   ','FEIRA BUFFET                            ')
insert into CentroDeCusto (Codigo,Descricao) values('310205   ','FEIRA FIPAN                             ')
insert into CentroDeCusto (Codigo,Descricao) values('310206   ','FEIRA EXPO POSTOS E CONVENIENCIAS       ')
insert into CentroDeCusto (Codigo,Descricao) values('310207   ','FEIRA FRANQUIAS - ABF                   ')
insert into CentroDeCusto (Codigo,Descricao) values('310208   ','FEIRA ISM                               ')
insert into CentroDeCusto (Codigo,Descricao) values('310209   ','FEIRA  CANTAO                           ')
insert into CentroDeCusto (Codigo,Descricao) values('310210   ','FEIRA EXPOFOOD SUPER RIO                ')
insert into CentroDeCusto (Codigo,Descricao) values('310211   ','FEIRA MAKRO  EXTRAVAGANZA               ')
insert into CentroDeCusto (Codigo,Descricao) values('310212   ','FEIRA EXPOCINE                          ')
insert into CentroDeCusto (Codigo,Descricao) values('310213   ','FEIRA EXPO BOMBONIERE                   ')
insert into CentroDeCusto (Codigo,Descricao) values('310214   ','FEIRA EQUIPOTEL                         ')
insert into CentroDeCusto (Codigo,Descricao) values('3103     ','MIDIA                                   ')
insert into CentroDeCusto (Codigo,Descricao) values('310301   ','ANUNCIOS                                ')
insert into CentroDeCusto (Codigo,Descricao) values('310302   ','PROPAGANDAS/COMERCIAL                   ')
insert into CentroDeCusto (Codigo,Descricao) values('310303   ','SITES                                   ')
insert into CentroDeCusto (Codigo,Descricao) values('310304   ','AGENCIA - FEE MENSAL                    ')
insert into CentroDeCusto (Codigo,Descricao) values('3104     ','PATROCINIOS                             ')
insert into CentroDeCusto (Codigo,Descricao) values('310401   ','LEI ROUANET                             ')
insert into CentroDeCusto (Codigo,Descricao) values('310402   ','INCENTIVO ESPORTE/CULTURA               ')
insert into CentroDeCusto (Codigo,Descricao) values('310403   ','ARENA PALMEIRAS                         ')
insert into CentroDeCusto (Codigo,Descricao) values('3105     ','PROJETOS - PARQUES                      ')
insert into CentroDeCusto (Codigo,Descricao) values('310501   ','HOPI HARI                               ')
insert into CentroDeCusto (Codigo,Descricao) values('310502   ','PARQUE DA MONICA                        ')
insert into CentroDeCusto (Codigo,Descricao) values('310503   ','THERMAS DO RIO QUENTE                   ')
insert into CentroDeCusto (Codigo,Descricao) values('310504   ','WETN WILD                               ')
insert into CentroDeCusto (Codigo,Descricao) values('310505   ','BEACH PARK                              ')
insert into CentroDeCusto (Codigo,Descricao) values('310506   ','ALDEIA DAS AGUAS                        ')
insert into CentroDeCusto (Codigo,Descricao) values('310507   ','PARQUE KIDZANIA                         ')
insert into CentroDeCusto (Codigo,Descricao) values('3106     ','PROJETOS - CINEMAS                      ')
insert into CentroDeCusto (Codigo,Descricao) values('310601   ','CINEPOLIS                               ')
insert into CentroDeCusto (Codigo,Descricao) values('310602   ','CINEMARK                                ')
insert into CentroDeCusto (Codigo,Descricao) values('310603   ','CENTER PLEX                             ')
insert into CentroDeCusto (Codigo,Descricao) values('310604   ','CINE FINI                               ')
insert into CentroDeCusto (Codigo,Descricao) values('310605   ','KINOPLEX                                ')
insert into CentroDeCusto (Codigo,Descricao) values('310606   ','CIRCUITO CINEMA                         ')
insert into CentroDeCusto (Codigo,Descricao) values('3107     ','PROJETO NOVOS PRODUTOS                  ')
insert into CentroDeCusto (Codigo,Descricao) values('310701   ','OVOS PASCOA                             ')
insert into CentroDeCusto (Codigo,Descricao) values('4        ','EXPORTACAO                              ')
insert into CentroDeCusto (Codigo,Descricao) values('41       ','EXPORTACAO                              ')
insert into CentroDeCusto (Codigo,Descricao) values('4100     ','EXPORTACAO                              ')
insert into CentroDeCusto (Codigo,Descricao) values('410001   ','ADM. EXPORTACAO - BRASIL                ')
insert into CentroDeCusto (Codigo,Descricao) values('410002   ','ADM. EXPORTACAO - CHILE                 ')
insert into CentroDeCusto (Codigo,Descricao) values('410003   ','ADM. EXPORTACAO - BOLIVIA               ')
insert into CentroDeCusto (Codigo,Descricao) values('4101     ','EXPORTACAO - CLIENTES                   ')
insert into CentroDeCusto (Codigo,Descricao) values('410101   ','SWEET S.A                               ')
insert into CentroDeCusto (Codigo,Descricao) values('410102   ','INTEGRATED SWEET IMPORTERS              ')
insert into CentroDeCusto (Codigo,Descricao) values('410103   ','FISAN LTDA                              ')
insert into CentroDeCusto (Codigo,Descricao) values('410104   ','SANCHEZ CANO Y CIA LTDA                 ')
insert into CentroDeCusto (Codigo,Descricao) values('410105   ','SAVONA S.A DE C.V                       ')
insert into CentroDeCusto (Codigo,Descricao) values('410106   ','PROYEX PANAMA S.A                       ')
insert into CentroDeCusto (Codigo,Descricao) values('410107   ','VERDE AZUL                              ')
insert into CentroDeCusto (Codigo,Descricao) values('410108   ','TRONDIAL                                ')
insert into CentroDeCusto (Codigo,Descricao) values('410109   ','CORPORACION TRANCEL CA                  ')
insert into CentroDeCusto (Codigo,Descricao) values('410110   ','GOLOSINAS DE CENTROAMERICA S.A DE C.V   ')
insert into CentroDeCusto (Codigo,Descricao) values('410111   ','LIDERGOOD S.A                           ')
insert into CentroDeCusto (Codigo,Descricao) values('410112   ','KING DAVID DELICATESSE                  ')
insert into CentroDeCusto (Codigo,Descricao) values('410113   ','OSTL INC -EUA                           ')
insert into CentroDeCusto (Codigo,Descricao) values('410114   ','ITOM DISTRIBUIDORA LTD                  ')
insert into CentroDeCusto (Codigo,Descricao) values('410115   ','I.U.T INTERNATIONAL TRADE CO            ')
insert into CentroDeCusto (Codigo,Descricao) values('410116   ','FINI GULOSINAS ESPANA S.L.U             ')
insert into CentroDeCusto (Codigo,Descricao) values('410117   ','PANAMA TRADING (PARAGUAI)               ')
insert into CentroDeCusto (Codigo,Descricao) values('5        ','INDUSTRIAL                              ')
insert into CentroDeCusto (Codigo,Descricao) values('51       ','INDUSTRIAL                              ')
insert into CentroDeCusto (Codigo,Descricao) values('5100     ','PRODUCAO                                ')
insert into CentroDeCusto (Codigo,Descricao) values('510001   ','GERENCIA PRODUCAO                       ')
insert into CentroDeCusto (Codigo,Descricao) values('510002   ','MOD MOGUL                               ')
insert into CentroDeCusto (Codigo,Descricao) values('510003   ','MO MARSHMALLOW                          ')
insert into CentroDeCusto (Codigo,Descricao) values('510004   ','MO CHICLES                              ')
insert into CentroDeCusto (Codigo,Descricao) values('510005   ','MO REGALIZ                              ')
insert into CentroDeCusto (Codigo,Descricao) values('510006   ','MO COZINHA                              ')
insert into CentroDeCusto (Codigo,Descricao) values('510007   ','MO DOSIMETRIA                           ')
insert into CentroDeCusto (Codigo,Descricao) values('510008   ','PCP                                     ')
insert into CentroDeCusto (Codigo,Descricao) values('510009   ','ESTRANGEIROS - ESP.                     ')
insert into CentroDeCusto (Codigo,Descricao) values('5101     ','EMBALAGEM                               ')
insert into CentroDeCusto (Codigo,Descricao) values('510101   ','MOD EMBALAGEM                           ')
insert into CentroDeCusto (Codigo,Descricao) values('510102   ','MOD EMBALAGEM - REGALIZ                 ')
insert into CentroDeCusto (Codigo,Descricao) values('5102     ','MANUTENCAO                              ')
insert into CentroDeCusto (Codigo,Descricao) values('510201   ','MO MANUTENCAO                           ')
insert into CentroDeCusto (Codigo,Descricao) values('510202   ','MANUTENCAO CIVIL                        ')
insert into CentroDeCusto (Codigo,Descricao) values('510203   ','MANUTENCAO COZINHA                      ')
insert into CentroDeCusto (Codigo,Descricao) values('510204   ','MANUTENCAO MOGUL                        ')
insert into CentroDeCusto (Codigo,Descricao) values('510205   ','MANUTENCAO MARSHMALLOW                  ')
insert into CentroDeCusto (Codigo,Descricao) values('510206   ','MANUTENCAO CHICLES                      ')
insert into CentroDeCusto (Codigo,Descricao) values('510207   ','MANUTENCAO REGALIZ                      ')
insert into CentroDeCusto (Codigo,Descricao) values('510208   ','MANUTENCAO EMBALAGEM                    ')
insert into CentroDeCusto (Codigo,Descricao) values('510209   ','MANUTENCAO REFRIGERACAO                 ')
insert into CentroDeCusto (Codigo,Descricao) values('510210   ','MANUTENCAO CALDEIRA                     ')
insert into CentroDeCusto (Codigo,Descricao) values('510211   ','MANUTENCAO GERADORES/CABINES            ')
insert into CentroDeCusto (Codigo,Descricao) values('510212   ','MANUTENCAO AR COMPRIMIDO                ')
insert into CentroDeCusto (Codigo,Descricao) values('510213   ','MANUTENCAO TRAT. EFLUENTE/DESC. RESIDUOS')
insert into CentroDeCusto (Codigo,Descricao) values('510214   ','MANUTENCAO APOIO                        ')
insert into CentroDeCusto (Codigo,Descricao) values('510215   ','MANUTENCAO EQUIP. MOVIMENTACAO          ')
insert into CentroDeCusto (Codigo,Descricao) values('510216   ','MANUTENCAO COBRIDEIRA DE CHOCOLATE      ')
insert into CentroDeCusto (Codigo,Descricao) values('5103     ','CONTROLE DE QUALIDADE                   ')
insert into CentroDeCusto (Codigo,Descricao) values('510301   ','CONTROLE DE QUALIDADE                   ')
insert into CentroDeCusto (Codigo,Descricao) values('510302   ','PESQUISA E DESENVOLVIMENTO              ')
insert into CentroDeCusto (Codigo,Descricao) values('510303   ','BPF / ISO                               ')
insert into CentroDeCusto (Codigo,Descricao) values('6        ','LOGISTICA                               ')
insert into CentroDeCusto (Codigo,Descricao) values('61       ','LOGISTICA                               ')
insert into CentroDeCusto (Codigo,Descricao) values('6100     ','LOGISTICA                               ')
insert into CentroDeCusto (Codigo,Descricao) values('610001   ','GERENCIA DE LOGISTICA                   ')
insert into CentroDeCusto (Codigo,Descricao) values('610002   ','LOGISTICA                               ')
insert into CentroDeCusto (Codigo,Descricao) values('610003   ','ALMOXARIFADO - LOGISTICA                ')
insert into CentroDeCusto (Codigo,Descricao) values('7        ','TRADE MARKETING                         ')
insert into CentroDeCusto (Codigo,Descricao) values('71       ','TRADE MARKETING                         ')
insert into CentroDeCusto (Codigo,Descricao) values('7100     ','TRADE MARKETING                         ')
insert into CentroDeCusto (Codigo,Descricao) values('710001   ','ADM TRADE MARKETING                     ')
insert into CentroDeCusto (Codigo,Descricao) values('7101     ','PROMOTORES TRADE MKT                    ')
insert into CentroDeCusto (Codigo,Descricao) values('710101   ','PROMOTORES TRADE MKT - SP               ')
insert into CentroDeCusto (Codigo,Descricao) values('710102   ','PROMOTORES TRADE MKT - RJ / MG / ES     ')
insert into CentroDeCusto (Codigo,Descricao) values('710103   ','PROMOTORES TRADE MKT - NO / NE          ')
insert into CentroDeCusto (Codigo,Descricao) values('710104   ','PROMOTORES TRADE MKT - CO / TRIANGULO MG')
insert into CentroDeCusto (Codigo,Descricao) values('710105   ','PROMOTORES TRADE MKT - SUL              ')
insert into CentroDeCusto (Codigo,Descricao) values('7102     ','TRADE MARKETING - OUTROS                ')
insert into CentroDeCusto (Codigo,Descricao) values('710201   ','MATERIAL PROMOCIONAL MERCHAN            ')
insert into CentroDeCusto (Codigo,Descricao) values('710202   ','DISPLAY                                 ')
insert into CentroDeCusto (Codigo,Descricao) values('710203   ','BRINDES TRADE                           ')
insert into CentroDeCusto (Codigo,Descricao) values('710204   ','BONIFICACAO  TRADE MKT                  ')
insert into CentroDeCusto (Codigo,Descricao) values('710205   ','DEGUSTADORES                            ')
insert into CentroDeCusto (Codigo,Descricao) values('710206   ','TREINAMENTO TRADE MARKETING             ')
insert into CentroDeCusto (Codigo,Descricao) values('8        ','PROJETOS                                ')
insert into CentroDeCusto (Codigo,Descricao) values('81       ','PROJETOS                                ')
insert into CentroDeCusto (Codigo,Descricao) values('8100     ','PROJETOS SANCHEZ CANO                   ')
insert into CentroDeCusto (Codigo,Descricao) values('810001   ','PROJETO NOVO MARSH.                     ')
insert into CentroDeCusto (Codigo,Descricao) values('810002   ','PROJETO ADEQUACAO AMBIENTAL             ')
insert into CentroDeCusto (Codigo,Descricao) values('810003   ','COBRIDEIRA DE CHOCOLATE                 ')
insert into CentroDeCusto (Codigo,Descricao) values('810004   ','ENCAIXOTADORA AUTOMATICA                ')
insert into CentroDeCusto (Codigo,Descricao) values('810005   ','INSPECAO ELETRICA - NR 10               ')
insert into CentroDeCusto (Codigo,Descricao) values('810006   ','MONTAGEM NOVA REGALIZ                   ')
insert into CentroDeCusto (Codigo,Descricao) values('810007   ','REALOCACAO LINHA MARSH                  ')
insert into CentroDeCusto (Codigo,Descricao) values('810008   ','SALA TREINAMENTO FABRICA                ')
insert into CentroDeCusto (Codigo,Descricao) values('810009   ','CONSTRUCAO CAMARA FRIA                  ')
insert into CentroDeCusto (Codigo,Descricao) values('810010   ','ADEQUACAO REGALIZ 20G                   ')
insert into CentroDeCusto (Codigo,Descricao) values('810011   ','CONTROLE DE UMIDADE -LINHAS MARSHMALLOW ')
insert into CentroDeCusto (Codigo,Descricao) values('810012   ','PENEIRAMENTO DA MOGUL                   ')
insert into CentroDeCusto (Codigo,Descricao) values('810013   ','INSTALACAO DO NOVO TANQUE DE GLUCOSE    ')
insert into CentroDeCusto (Codigo,Descricao) values('810014   ','CAMARAS PARA O SETOR DE ENVASE          ')
insert into CentroDeCusto (Codigo,Descricao) values('810015   ','MELHORIA PARA CLIMATIZACAO PARA CAMARA 5')
insert into CentroDeCusto (Codigo,Descricao) values('810016   ','CLIMATIZACAO DA COZINHA                 ')
insert into CentroDeCusto (Codigo,Descricao) values('810017   ','INSTALACAO DA LINHA REGALIZ N°4         ')
insert into CentroDeCusto (Codigo,Descricao) values('810018   ','GERACAO SIST.VACUO P/COZINHA            ')
insert into CentroDeCusto (Codigo,Descricao) values('810019   ','SISTEMA DE DESPOEIRAMENTO DA MOGUL      ')
insert into CentroDeCusto (Codigo,Descricao) values('810020   ','GEA SMARTPACKER                         ')
insert into CentroDeCusto (Codigo,Descricao) values('810021   ','PLATAFORMA DOS FANCOIL                  ')
insert into CentroDeCusto (Codigo,Descricao) values('810022   ','ADEQUACOES PARA GOMA ITALIANA           ')
insert into CentroDeCusto (Codigo,Descricao) values('810023   ','NOVO ALMOXARIFADO                       ')
insert into CentroDeCusto (Codigo,Descricao) values('810024   ','LAVA CAIXAS                             ')
insert into CentroDeCusto (Codigo,Descricao) values('810025   ','CLIMATIZACAO EVAPORATIVA GALPAO REGALIZ ')
insert into CentroDeCusto (Codigo,Descricao) values('810026   ','REALOCACAO DO BANHEIRO DA PRODUCAO      ')
insert into CentroDeCusto (Codigo,Descricao) values('810027   ','ADEQUACOES PARA LINHA DE MARSHMALLOW    ')
insert into CentroDeCusto (Codigo,Descricao) values('810028   ','IMPLANTACAO GKO                         ')
insert into CentroDeCusto (Codigo,Descricao) values('810029   ','VENTILACAO SALA COMPRESSORES/CABINE SECU')
insert into CentroDeCusto (Codigo,Descricao) values('8101     ','PROJETOS FINI COMERCIALIZADORA          ')
insert into CentroDeCusto (Codigo,Descricao) values('810101   ','CONSTRUCAO-FASE I - PROJ. INDL.         ')
insert into CentroDeCusto (Codigo,Descricao) values('810102   ','CONSTRUCAO - FASE I - PROJ. ADM         ')
insert into CentroDeCusto (Codigo,Descricao) values('810103   ','SOFTWARE WIS DA SYTHEX -FINI            ')
insert into CentroDeCusto (Codigo,Descricao) values('810104   ','REINTEGRACAO E-COMMERCE (VTEX) COM PROTH')
insert into CentroDeCusto (Codigo,Descricao) values('9        ','APURACAO DE RESULTADO                   ')
insert into CentroDeCusto (Codigo,Descricao) values('91       ','APURACAO DE RESULTADO                   ')
insert into CentroDeCusto (Codigo,Descricao) values('9100     ','APURACAO DE RESULTADO                   ')
insert into CentroDeCusto (Codigo,Descricao) values('910001   ','APURACAO DE RESULTADO                   ')
insert into CentroDeCusto (Codigo,Descricao) values('1108     ','ADM. EXCELENCIA OPERACIONAL             ')
insert into CentroDeCusto (Codigo,Descricao) values('110801   ','ADM. EXCELENCIA OPERACIONAL             ')
insert into CentroDeCusto (Codigo,Descricao) values('710207   ','TRADE CANAL FARMA                       ')
insert into CentroDeCusto (Codigo,Descricao) values('810030   ','SUBSTITUICAO DOS TANQUES DE AGUA 60°C E ')
insert into CentroDeCusto (Codigo,Descricao) values('810031   ','EVOLUCAO SERVIDORES PROTHEUS            ')
insert into CentroDeCusto (Codigo,Descricao) values('810032   ','REVESTIMENTO COZINHA                    ')
insert into CentroDeCusto (Codigo,Descricao) values('810033   ','SECADOR DE AR COMPRIMIDO                ')
insert into CentroDeCusto (Codigo,Descricao) values('810034   ','EXAUSTAO DE VAPOR                       ')
insert into CentroDeCusto (Codigo,Descricao) values('810035   ','MELHORIAS COZINHA                       ')
insert into CentroDeCusto (Codigo,Descricao) values('810036   ','MELHORIAS CHICLE                        ')
insert into CentroDeCusto (Codigo,Descricao) values('810037   ','SUBST DOS PAINEIS ELETRICOS CCM-MOGUL   ')
insert into CentroDeCusto (Codigo,Descricao) values('810038   ','EXPANSAO DA CABINE SECUNDARIA           ')
insert into CentroDeCusto (Codigo,Descricao) values('810039   ','QUEBRADOR DE ACUCAR                     ')
insert into CentroDeCusto (Codigo,Descricao) values('810040   ','PALETES MOGUL                           ')
insert into CentroDeCusto (Codigo,Descricao) values('810041   ','FILTRO PARA MASSA DE REGALIZ            ')
insert into CentroDeCusto (Codigo,Descricao) values('810042   ','MEDICAO DE EFLUENTES - ETE              ')
insert into CentroDeCusto (Codigo,Descricao) values('810043   ','ADEQUACAO DAS CAMARAS CLIMATIZADAS      ')
insert into CentroDeCusto (Codigo,Descricao) values('810044   ','PROJETO PREACTOR PCP                    ')
insert into CentroDeCusto (Codigo,Descricao) values('810045   ','ADEQUACAO DOS POCOS ARTESIANOS          ')
insert into CentroDeCusto (Codigo,Descricao) values('810046   ','AUMENTO DE CAPACIDADE NH3               ')
insert into CentroDeCusto (Codigo,Descricao) values('810047   ','INSTALACOES PARA INGREDION              ')
insert into CentroDeCusto (Codigo,Descricao) values('810048   ','SOFTWARE WIS DA SYTHEX                  ')
insert into CentroDeCusto (Codigo,Descricao) values('810049   ','NOVA COZINHA MARSH                      ')
insert into CentroDeCusto (Codigo,Descricao) values('810050   ','SECADORES MOGUL                         ')
insert into CentroDeCusto (Codigo,Descricao) values('810051   ','PROJETO AMPLIACAO REDE FABRICA          ')
insert into CentroDeCusto (Codigo,Descricao) values('810052   ','PROJETO CFTV                            ')
insert into CentroDeCusto (Codigo,Descricao) values('810053   ','PROTECAO CONTRA INCENDIO NO REGALIZ     ')
insert into CentroDeCusto (Codigo,Descricao) values('810054   ','TUBULACAO DE AGUA FASE 1                ')
insert into CentroDeCusto (Codigo,Descricao) values('810055   ','SALA PARA OS ESPANHOIS                  ')
insert into CentroDeCusto (Codigo,Descricao) values('810056   ','GEA SMARTPACKER 2                       ')
insert into CentroDeCusto (Codigo,Descricao) values('810057   ','EXIGENCIAS PARA RENOVACAO DO AVCB       ')
insert into CentroDeCusto (Codigo,Descricao) values('810058   ','CONTROLE DE MANUTENCAO                  ')
insert into CentroDeCusto (Codigo,Descricao) values('810059   ','AUTOMACAO ALMOX MANUT – ACD             ')
insert into CentroDeCusto (Codigo,Descricao) values('810060   ','MIGRACAO TOTVS 12                       ')
insert into CentroDeCusto (Codigo,Descricao) values('810061   ','SISTEMA TOTVS COLABORACAO               ')
insert into CentroDeCusto (Codigo,Descricao) values('810105   ','PROJETO GKO                             ')
insert into CentroDeCusto (Codigo,Descricao) values('810106   ','PROJETO DSI DISTRIBUIDORES              ')
insert into CentroDeCusto (Codigo,Descricao) values('810107   ','PROJETO MERCANET                        ')
insert into CentroDeCusto (Codigo,Descricao) values('810108   ','CONSTRUCAO ADM FINI                     ')
insert into CentroDeCusto (Codigo,Descricao) values('810109   ','PROJETO AVCB                            ')
insert into CentroDeCusto (Codigo,Descricao) values('510010   ','ALMOXARIFADO MANUTENCAO E ENGENHARIA    ')
insert into CentroDeCusto (Codigo,Descricao) values('5104     ','LEAN MANUFACTURING                      ')
insert into CentroDeCusto (Codigo,Descricao) values('510401   ','LEAN MANUFACTURING                      ')
insert into CentroDeCusto (Codigo,Descricao) values('5105     ','SUPPLY                                  ')
insert into CentroDeCusto (Codigo,Descricao) values('510501   ','ALMOXARIFADO MANUTENCAO E ENGENHARIA    ')
insert into CentroDeCusto (Codigo,Descricao) values('510502   ','PLANEJAMENTO (PCP)                      ')
insert into CentroDeCusto (Codigo,Descricao) values('510304   ','RETRABALHO                              ')
insert into CentroDeCusto (Codigo,Descricao) values('810062   ','TAREAS LIBRES                           ')
insert into CentroDeCusto (Codigo,Descricao) values('810063   ','ISOLAMENTO TERMICO ALMOXARIFADO         ')
insert into CentroDeCusto (Codigo,Descricao) values('810064   ','TAREAS LIBRES                           ')
insert into CentroDeCusto (Codigo,Descricao) values('210002   ','ADM. VENDAS - FILIAL                    ')
insert into CentroDeCusto (Codigo,Descricao) values('210003   ','ADM. VENDAS - FILIAL 004                ')
insert into CentroDeCusto (Codigo,Descricao) values('310106   ','PROMOCES E EVENTOS                      ')
insert into CentroDeCusto (Codigo,Descricao) values('310107   ','DEGUSTADORES MKT                        ')
insert into CentroDeCusto (Codigo,Descricao) values('310003   ','TRADE MARKETING                         ')
insert into CentroDeCusto (Codigo,Descricao) values('310108   ','BALBOA COM. SERV. IMP. EXP. LTDA        ')
insert into CentroDeCusto (Codigo,Descricao) values('410118   ','TAMY S.P.A.                             ')
insert into CentroDeCusto (Codigo,Descricao) values('3108     ','MERCHANDISING                           ')
insert into CentroDeCusto (Codigo,Descricao) values('310801   ','PROMOTORES                              ')
insert into CentroDeCusto (Codigo,Descricao) values('310802   ','MATERIAL PROMOC. MERCHAN                ')
insert into CentroDeCusto (Codigo,Descricao) values('3109     ','FRANQUIA                                ')
insert into CentroDeCusto (Codigo,Descricao) values('310901   ','ADM. FRANQUIA                           ')
insert into CentroDeCusto (Codigo,Descricao) values('610004   ','FRETES PRODUTOS 18GR                    ')
insert into CentroDeCusto (Codigo,Descricao) values('610005   ','FRETES PRODUTOS 20GR                    ')
insert into CentroDeCusto (Codigo,Descricao) values('610006   ','FRETES OPERACIONAIS MOV. COMPRAS        ')
insert into CentroDeCusto (Codigo,Descricao) values('410119   ','EMILIO SANDOVAL POO S.A.                ')
insert into CentroDeCusto (Codigo,Descricao) values('210202   ','PROJETO MERCANET                        ')
insert into CentroDeCusto (Codigo,Descricao) values('210203   ','PROJETO ACCERA – DSI                    ')
insert into CentroDeCusto (Codigo,Descricao) values('210114   ','VENDAS REGIONAL NO / NE                 ')
insert into CentroDeCusto (Codigo,Descricao) values('210115   ','VENDAS REGIONAL CO / SPI / TRIANGULO MG ')
insert into CentroDeCusto (Codigo,Descricao) values('210116   ','VENDAS REGIONAL SUL                     ')
insert into CentroDeCusto (Codigo,Descricao) values('210117   ','VENDAS REGIONAL RJ/ES/MG - ATACADO      ')
insert into CentroDeCusto (Codigo,Descricao) values('210118   ','VENDAS - FARMA                          ')
insert into CentroDeCusto (Codigo,Descricao) values('210119   ','KEY ACCOUNT LASA                        ')
insert into CentroDeCusto (Codigo,Descricao) values('310215   ','FEIRA ABRADILAN                         ')
insert into CentroDeCusto (Codigo,Descricao) values('310902   ','ASSESSORIA FRANQUIA                     ')
insert into CentroDeCusto (Codigo,Descricao) values('310903   ','MOVEIS E INSTALACOES FRANQUIA           ')
insert into CentroDeCusto (Codigo,Descricao) values('410004   ','ADM. EXPORTACAO - COLOMBIA              ')
insert into CentroDeCusto (Codigo,Descricao) values('510217   ','PEQUENAS MELHORIAS BRASIL               ')
insert into CentroDeCusto (Codigo,Descricao) values('510218   ','PEQUENAS MELHORIAS ESPANHA              ')
insert into CentroDeCusto (Codigo,Descricao) values('410120   ','BIMESUR – ANGOLA                        ')
insert into CentroDeCusto (Codigo,Descricao) values('810064   ','REFORMA DA COZINHA                      ')
insert into CentroDeCusto (Codigo,Descricao) values('810065   ','VENTILACAO PARA O ALMOXARIFADO          ')
insert into CentroDeCusto (Codigo,Descricao) values('810066   ','ENVOLVEDORA REGALIZ                     ')
insert into CentroDeCusto (Codigo,Descricao) values('210120   ','VENDAS CASH & CARRY                     ')
insert into CentroDeCusto (Codigo,Descricao) values('210121   ','VENDAS NACIONAL ATACADO                 ')
insert into CentroDeCusto (Codigo,Descricao) values('210122   ','VENDAS NACIONAL DISTRIBUICAO            ')
insert into CentroDeCusto (Codigo,Descricao) values('810067   ','LINHA 12 BAR ESPUMADEIRAS               ')
insert into CentroDeCusto (Codigo,Descricao) values('810068   ','SETUP RAUMAK                            ')
insert into CentroDeCusto (Codigo,Descricao) values('810069   ','HOLERITE ELETRONICO                     ')
insert into CentroDeCusto (Codigo,Descricao) values('810070   ','SALA DE MOLDE                           ')
insert into CentroDeCusto (Codigo,Descricao) values('810071   ','TIRAS 100G                              ')
insert into CentroDeCusto (Codigo,Descricao) values('810072   ','FIM DE LINHA 18G GEA                    ')
insert into CentroDeCusto (Codigo,Descricao) values('110102   ','RPA ADMINISTRACAO                       ')
insert into CentroDeCusto (Codigo,Descricao) values('5106     ','P&D                                     ')
insert into CentroDeCusto (Codigo,Descricao) values('510601   ','GERENCIA DE P&D                         ')
insert into CentroDeCusto (Codigo,Descricao) values('810110   ','DETECCAO DE AMONIA                      ')
insert into CentroDeCusto (Codigo,Descricao) values('810073   ','REFORMA DO TELHADO FABRICA              ')
insert into CentroDeCusto (Codigo,Descricao) values('510503   ','OPERACAO MP E EM                        ')
insert into CentroDeCusto (Codigo,Descricao) values('810074   ','AMASSADORA RESERVA CHICLES              ')
insert into CentroDeCusto (Codigo,Descricao) values('810075   ','ESTEIRA DE ACUCAR MARSH 2               ')
insert into CentroDeCusto (Codigo,Descricao) values('810076   ','AGUA GELADA PARA CHICLES                ')
insert into CentroDeCusto (Codigo,Descricao) values('810077   ','REGALIZ 20G                             ')
insert into CentroDeCusto (Codigo,Descricao) values('810078   ','PECTINA MOGUL 2                         ')
insert into CentroDeCusto (Codigo,Descricao) values('810079   ','PROJETO WORKFLOW ETAPA II               ')
insert into CentroDeCusto (Codigo,Descricao) values('810080   ','PROJETO MASTER PLANNING                 ')
insert into CentroDeCusto (Codigo,Descricao) values('510602   ','DESENVOLVIMENTO DE MATERIAIS            ')
insert into CentroDeCusto (Codigo,Descricao) values('510603   ','LANCAMENTOS DE PRODUTOS                 ')
insert into CentroDeCusto (Codigo,Descricao) values('510604   ','OTIMIZACAO DE PROCESSOS                 ')
insert into CentroDeCusto (Codigo,Descricao) values('510605   ','EQUIPAMENTOS P&D                        ')
insert into CentroDeCusto (Codigo,Descricao) values('510606   ','PESQUISA                                ')
insert into CentroDeCusto (Codigo,Descricao) values('510607   ','INOVACAO                                ')
insert into CentroDeCusto (Codigo,Descricao) values('810081   ','CFV - CONTROLE DE FLUXO DE VEICULOS LOGI')
insert into CentroDeCusto (Codigo,Descricao) values('810082   ','ESTACIONAMENTO FABRICA                  ')
insert into CentroDeCusto (Codigo,Descricao) values('810083   ','MEDICAO DE NIVEL DE GLUCOSES            ')
insert into CentroDeCusto (Codigo,Descricao) values('610007   ','FROTA PROPRIA                           ')
insert into CentroDeCusto (Codigo,Descricao) values('810084   ','MOINHO DE MARTELO                       ')
insert into CentroDeCusto (Codigo,Descricao) values('810085   ','NORMAS REGULAMENTADORAS                 ')
insert into CentroDeCusto (Codigo,Descricao) values('810086   ','MUDANCA DE MOTORES E REDUTORES          ')
insert into CentroDeCusto (Codigo,Descricao) values('810087   ','OEE MOGUL                               ')
insert into CentroDeCusto (Codigo,Descricao) values('310216   ','FEIRA EXPO CENTER NORTE                 ')
insert into CentroDeCusto (Codigo,Descricao) values('310217   ','FEIRA ABRAFARMA                         ')
insert into CentroDeCusto (Codigo,Descricao) values('810088   ','ILUMINACAO TANQUE DE DIESEL             ')
insert into CentroDeCusto (Codigo,Descricao) values('310218   ','FEIRA FARMARCAS                         ')
insert into CentroDeCusto (Codigo,Descricao) values('810089   ','TURBINA DE ASPIRACAO REGALIZ            ')
insert into CentroDeCusto (Codigo,Descricao) values('810090   ','PLATAFORMA DOCAS DO ARMAZEM             ')
insert into CentroDeCusto (Codigo,Descricao) values('810091   ','EQUIPAMENTOS DE MOVIMENTACAO DE CARGAS  ')
insert into CentroDeCusto (Codigo,Descricao) values('810092   ','ADEQUACOES PARA NR10                    ')
insert into CentroDeCusto (Codigo,Descricao) values('810093   ','ADEQUACOES PARA NR12                    ')
insert into CentroDeCusto (Codigo,Descricao) values('810094   ','ADEQUACOES PARA NR13                    ')
insert into CentroDeCusto (Codigo,Descricao) values('310607   ','CINEMA UCI                              ')
insert into CentroDeCusto (Codigo,Descricao) values('810095   ','NOVA GLUCOSE CARGILL                    ')
insert into CentroDeCusto (Codigo,Descricao) values('810096   ','3ª ESPUMADEIRA MOGUL                    ')
insert into CentroDeCusto (Codigo,Descricao) values('810097   ','DESENHOS FABRICA E PROJETOS             ')
insert into CentroDeCusto (Codigo,Descricao) values('710002   ','TRADE – EXPATRIADOS                     ')
insert into CentroDeCusto (Codigo,Descricao) values('310219   ','EXPO FARMA                              ')
insert into CentroDeCusto (Codigo,Descricao) values('310220   ','FEIRA OFERTAO                           ')
insert into CentroDeCusto (Codigo,Descricao) values('810098   ','CORRECAO TUNEIS REGALIZ                 ')
insert into CentroDeCusto (Codigo,Descricao) values('810099   ','CASA NOVA ESPANHOIS                     ')
insert into CentroDeCusto (Codigo,Descricao) values('810100   ','EVAPORADOR NH3                          ')
insert into CentroDeCusto (Codigo,Descricao) values('8102     ','PROJETOS SANCHEZ CANO                   ')
insert into CentroDeCusto (Codigo,Descricao) values('810201   ','EVAPORADOR NH3                          ')
insert into CentroDeCusto (Codigo,Descricao) values('810202   ','AGUA CLIMATIZADA                        ')
insert into CentroDeCusto (Codigo,Descricao) values('810203   ','RETROFIT TUNEIS REGALIZ                 ')
insert into CentroDeCusto (Codigo,Descricao) values('310221   ','FARMACIAS ASSOCIADAS                    ')
insert into CentroDeCusto (Codigo,Descricao) values('810204   ','VENTILACAO ENVASE                       ')
insert into CentroDeCusto (Codigo,Descricao) values('810205   ','NR35                                    ')
insert into CentroDeCusto (Codigo,Descricao) values('810206   ','CIP MOVEL                               ')
insert into CentroDeCusto (Codigo,Descricao) values('310222   ','FEIRA COMIC COM                         ')
insert into CentroDeCusto (Codigo,Descricao) values('810207   ','MELHORIA DA CLIMATIZACAO REGALIZ        ')
insert into CentroDeCusto (Codigo,Descricao) values('310608   ','PLAYARTE                                ')
insert into CentroDeCusto (Codigo,Descricao) values('310609   ','MOVIECOM                                ')
insert into CentroDeCusto (Codigo,Descricao) values('310610   ','CINEART                                 ')
insert into CentroDeCusto (Codigo,Descricao) values('310611   ','CINESYSTEM                              ')
insert into CentroDeCusto (Codigo,Descricao) values('810110   ','PROJETO PERFORMA RH                     ')
insert into CentroDeCusto (Codigo,Descricao) values('810111   ','GESTAO DE PROJETOS DE MKT               ')
insert into CentroDeCusto (Codigo,Descricao) values('810208   ','CONSERTO PISO FABRICA                   ')
insert into CentroDeCusto (Codigo,Descricao) values('510219   ','ENGENHARIA                              ')
insert into CentroDeCusto (Codigo,Descricao) values('810209   ','MELHORAS CD MP/EM                       ')
insert into CentroDeCusto (Codigo,Descricao) values('810210   ','REFORMA ADM SANCHEZ                     ')
insert into CentroDeCusto (Codigo,Descricao) values('810211   ','TANQUE DESAREADOR                       ')
insert into CentroDeCusto (Codigo,Descricao) values('810212   ','ABRANDADOR                              ')
insert into CentroDeCusto (Codigo,Descricao) values('810213   ','MOINHO REGALIZ                          ')
insert into CentroDeCusto (Codigo,Descricao) values('810214   ','REFORMA COZINHA MOGUL                   ')
insert into CentroDeCusto (Codigo,Descricao) values('810215   ','BALAS DIET MOGUL                        ')
insert into CentroDeCusto (Codigo,Descricao) values('810216   ','AREA EXTERNA SANCHEZ                    ')
insert into CentroDeCusto (Codigo,Descricao) values('810217   ','REGALIZ 5                               ')
insert into CentroDeCusto (Codigo,Descricao) values('810218   ','IMAR 4                                  ')
insert into CentroDeCusto (Codigo,Descricao) values('810219   ','FORMADORA DISPLAY REGALIZ 4             ')
insert into CentroDeCusto (Codigo,Descricao) values('810220   ','RETROFIT REGALIZ 1                      ')
insert into CentroDeCusto (Codigo,Descricao) values('810121   ','CAMARAS CLIMATIZADAS FASE II            ')
insert into CentroDeCusto (Codigo,Descricao) values('810221   ','CAMARAS CLIMATIZADAS FASE II            ')
insert into CentroDeCusto (Codigo,Descricao) values('810112   ','AREA EXTERNA FINI                       ')
insert into CentroDeCusto (Codigo,Descricao) values('710208   ','TRADE CANAL ATACADO                     ')
insert into CentroDeCusto (Codigo,Descricao) values('710209   ','TRADE CANAL DISTRIBUIDOR                ')
insert into CentroDeCusto (Codigo,Descricao) values('710210   ','TRADE CANAL C&C                         ')
insert into CentroDeCusto (Codigo,Descricao) values('710211   ','TRADE CANAL REDES                       ')
insert into CentroDeCusto (Codigo,Descricao) values('710003   ','ADM MERCHANDISING                       ')
insert into CentroDeCusto (Codigo,Descricao) values('710212   ','TRADE CANAL LASA                        ')
insert into CentroDeCusto (Codigo,Descricao) values('810222   ','REFORMA PISO DO CHICLES                 ')
insert into CentroDeCusto (Codigo,Descricao) values('810223   ','MELHORAS CD MP/EM                       ')
insert into CentroDeCusto (Codigo,Descricao) values('810224   ','REFORMA DAS CALDEIRAS                   ')
insert into CentroDeCusto (Codigo,Descricao) values('410121   ','HAND LONG S.A                           ')
insert into CentroDeCusto (Codigo,Descricao) values('410122   ','COTIA TRADING ANGOLA                    ')
insert into CentroDeCusto (Codigo,Descricao) values('210123   ','VENDAS REGIONAL NE -ATACADO             ')
insert into CentroDeCusto (Codigo,Descricao) values('210124   ','VENDAS REGIONAL RS -ATACADO             ')
insert into CentroDeCusto (Codigo,Descricao) values('510608   ','PROJETO PH IN LINE                      ')
insert into CentroDeCusto (Codigo,Descricao) values('510609   ','PROJETO BRIX IN LINE                    ')
insert into CentroDeCusto (Codigo,Descricao) values('810225   ','PROJETO PH IN LINE                      ')
insert into CentroDeCusto (Codigo,Descricao) values('810226   ','PROJETO BRIX IN LINE                    ')
insert into CentroDeCusto (Codigo,Descricao) values('310508   ','SNOWLAND                                ')
insert into CentroDeCusto (Codigo,Descricao) values('310509   ','BETO CARREIRO                           ')
insert into CentroDeCusto (Codigo,Descricao) values('810227   ','PONTES ROLANTE REGALIZ                  ')
insert into CentroDeCusto (Codigo,Descricao) values('810228   ','PESADORA DE CAIXAS REGALIZ              ')
insert into CentroDeCusto (Codigo,Descricao) values('810229   ','PROJETO WMS MP/EM                       ')
insert into CentroDeCusto (Codigo,Descricao) values('810230   ','ADEQUACOES NR17                         ')
insert into CentroDeCusto (Codigo,Descricao) values('810231   ','DIVISAO ENTRE FINI & SANCHEZ            ')
insert into CentroDeCusto (Codigo,Descricao) values('810232   ','ANTE CAMARA - FUNDOS DA FABRICA         ')
insert into CentroDeCusto (Codigo,Descricao) values('810233   ','INSTALACAO DE RALOS NO ENVASE DO REGALIZ')
insert into CentroDeCusto (Codigo,Descricao) values('810234   ','ASFALTAMENTO & ATERRAMENTO SANCHEZ      ')
insert into CentroDeCusto (Codigo,Descricao) values('810235   ','INSTALACAO FILTROS TUBULACOES GLUCOSE   ')
insert into CentroDeCusto (Codigo,Descricao) values('810236   ','INSTALACAO EXAUSTOR P/LAVADORA CAIXAS   ')
insert into CentroDeCusto (Codigo,Descricao) values('410123   ','HAND LONG S.A                           ')
insert into CentroDeCusto (Codigo,Descricao) values('810113   ','PROJETO SAC                             ')
insert into CentroDeCusto (Codigo,Descricao) values('110202   ','ADMINISTRACAO SAC                       ')
insert into CentroDeCusto (Codigo,Descricao) values('810237   ','CHICLE EM FLIP-TOP                      ')
insert into CentroDeCusto (Codigo,Descricao) values('810114   ','IMOVEL FINI VINHEDO                     ')
insert into CentroDeCusto (Codigo,Descricao) values('810238   ','APONTAMENTO PALLETS PA                  ')
insert into CentroDeCusto (Codigo,Descricao) values('810239   ','ARM. E ABASTECIMENTO DE FRACIONADOS     ')
insert into CentroDeCusto (Codigo,Descricao) values('810240   ','RASTREABILIDADE DE PA                   ')